name: BeBlaq
favicon: null
layout_spectrum: 0.40898322709836066
typography_spectrum: 0.8486
title: 'Redefine yourself | BeBlaq'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002129'
    - '#b3a2a2'
    - '#ddbe86'
    - '#5b2929'
    - '#b88858'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
